//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mapKnight.ToolKit.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 129, 180")]
        public global::System.Drawing.Color TabActiveBackColor {
            get {
                return ((global::System.Drawing.Color)(this["TabActiveBackColor"]));
            }
            set {
                this["TabActiveBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("184, 205, 224")]
        public global::System.Drawing.Color BackColor {
            get {
                return ((global::System.Drawing.Color)(this["BackColor"]));
            }
            set {
                this["BackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI, 9.75pt")]
        public global::System.Drawing.Font TabControlFont {
            get {
                return ((global::System.Drawing.Font)(this["TabControlFont"]));
            }
            set {
                this["TabControlFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("237, 243, 247")]
        public global::System.Drawing.Color TabActiveForeColor {
            get {
                return ((global::System.Drawing.Color)(this["TabActiveForeColor"]));
            }
            set {
                this["TabActiveForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("219, 230, 240")]
        public global::System.Drawing.Color TabInActiveBackColor {
            get {
                return ((global::System.Drawing.Color)(this["TabInActiveBackColor"]));
            }
            set {
                this["TabInActiveBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23, 39, 54")]
        public global::System.Drawing.Color TabInActiveForeColor {
            get {
                return ((global::System.Drawing.Color)(this["TabInActiveForeColor"]));
            }
            set {
                this["TabInActiveForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI, 8.25pt")]
        public global::System.Drawing.Font MenuStripFont {
            get {
                return ((global::System.Drawing.Font)(this["MenuStripFont"]));
            }
            set {
                this["MenuStripFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("53, 90, 126")]
        public global::System.Drawing.Color TabControlOutlineColor {
            get {
                return ((global::System.Drawing.Color)(this["TabControlOutlineColor"]));
            }
            set {
                this["TabControlOutlineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("224, 224, 224")]
        public global::System.Drawing.Color MenuStripActiveForeColor {
            get {
                return ((global::System.Drawing.Color)(this["MenuStripActiveForeColor"]));
            }
            set {
                this["MenuStripActiveForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("72, 118, 157")]
        public global::System.Drawing.Color MenuStripActiveBackColor {
            get {
                return ((global::System.Drawing.Color)(this["MenuStripActiveBackColor"]));
            }
            set {
                this["MenuStripActiveBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 129, 180")]
        public global::System.Drawing.Color MenuStripInActiveForeColor {
            get {
                return ((global::System.Drawing.Color)(this["MenuStripInActiveForeColor"]));
            }
            set {
                this["MenuStripInActiveForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("184, 205, 224")]
        public global::System.Drawing.Color MenuStripInActiveBackColor {
            get {
                return ((global::System.Drawing.Color)(this["MenuStripInActiveBackColor"]));
            }
            set {
                this["MenuStripInActiveBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("53, 90, 126")]
        public global::System.Drawing.Color MenuStripOutlineColor {
            get {
                return ((global::System.Drawing.Color)(this["MenuStripOutlineColor"]));
            }
            set {
                this["MenuStripOutlineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("184, 205, 224")]
        public global::System.Drawing.Color MenuStripInActiveDropDownBackColor {
            get {
                return ((global::System.Drawing.Color)(this["MenuStripInActiveDropDownBackColor"]));
            }
            set {
                this["MenuStripInActiveDropDownBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 129, 180")]
        public global::System.Drawing.Color MenuStripInActiveDropDownForeColor {
            get {
                return ((global::System.Drawing.Color)(this["MenuStripInActiveDropDownForeColor"]));
            }
            set {
                this["MenuStripInActiveDropDownForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("72, 118, 157")]
        public global::System.Drawing.Color MenuStripActiveDropDownBackColor {
            get {
                return ((global::System.Drawing.Color)(this["MenuStripActiveDropDownBackColor"]));
            }
            set {
                this["MenuStripActiveDropDownBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("224, 224, 224")]
        public global::System.Drawing.Color MenuStripActiveDropDownForeColor {
            get {
                return ((global::System.Drawing.Color)(this["MenuStripActiveDropDownForeColor"]));
            }
            set {
                this["MenuStripActiveDropDownForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("53, 90, 126")]
        public global::System.Drawing.Color MenuStripDropDownOutlineColor {
            get {
                return ((global::System.Drawing.Color)(this["MenuStripDropDownOutlineColor"]));
            }
            set {
                this["MenuStripDropDownOutlineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("78, 131, 177")]
        public global::System.Drawing.Color ListViewBackColor {
            get {
                return ((global::System.Drawing.Color)(this["ListViewBackColor"]));
            }
            set {
                this["ListViewBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23, 39, 53")]
        public global::System.Drawing.Color ListViewSelectedColor {
            get {
                return ((global::System.Drawing.Color)(this["ListViewSelectedColor"]));
            }
            set {
                this["ListViewSelectedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("237, 243, 247")]
        public global::System.Drawing.Color ListViewForeColor {
            get {
                return ((global::System.Drawing.Color)(this["ListViewForeColor"]));
            }
            set {
                this["ListViewForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI, 11.25pt")]
        public global::System.Drawing.Font ListViewFont {
            get {
                return ((global::System.Drawing.Font)(this["ListViewFont"]));
            }
            set {
                this["ListViewFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("78, 131, 177")]
        public global::System.Drawing.Color MapBackColor {
            get {
                return ((global::System.Drawing.Color)(this["MapBackColor"]));
            }
            set {
                this["MapBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("153, 255, 51")]
        public global::System.Drawing.Color MenuStripCheckedBackColor {
            get {
                return ((global::System.Drawing.Color)(this["MenuStripCheckedBackColor"]));
            }
            set {
                this["MenuStripCheckedBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13, 26, 0")]
        public global::System.Drawing.Color MenuStripCheckedForeColor {
            get {
                return ((global::System.Drawing.Color)(this["MenuStripCheckedForeColor"]));
            }
            set {
                this["MenuStripCheckedForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("77, 153, 0")]
        public global::System.Drawing.Color MenuStripCheckedOutlineColor {
            get {
                return ((global::System.Drawing.Color)(this["MenuStripCheckedOutlineColor"]));
            }
            set {
                this["MenuStripCheckedOutlineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("53, 90, 126")]
        public global::System.Drawing.Color SplitterColor {
            get {
                return ((global::System.Drawing.Color)(this["SplitterColor"]));
            }
            set {
                this["SplitterColor"] = value;
            }
        }
    }
}
